// app/layout.tsx
import { ThemeProvider } from "@/components/theme-provider"
import type { Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
// Import currentUser from the /server package
import { currentUser } from '@clerk/nextjs/server'
import { Inter } from 'next/font/google'
import './globals.css'
import { ModeToggle } from "@/components/mode-button"
import { TrendingUp } from "lucide-react"
import { Toaster } from "sonner"

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans', // Using a more generic variable name
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

// 1. Make the RootLayout function async
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  // 2. Get the user data on the server
  const user = await currentUser()

  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${inter.variable} antialiased`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <header className="flex justify-between items-center py-2 px-4 border border-b-1">
              {/* You can add a logo or site title here on the left */}
              <div className="flex gap-2 items-center">
                <TrendingUp />
                <a href="/" className="text-lg font-semibold">Trade Log</a>
              </div>

              {/* User section on the right */}
              <div className="flex items-center gap-4">
                <SignedOut>
                  <SignInButton />
                </SignedOut>
                <SignedIn>
                  {/* 3. Render the user's name and UserButton */}
                  {user?.firstName && (
                    <p className="text-sm font-medium text-gray-700">
                      Hi, {user.firstName}
                    </p>
                  )}
                  <UserButton />
                  <ModeToggle />
                </SignedIn>
              </div>
            </header>
            <SignedIn>
              {children}
            </SignedIn>
            <SignedOut>
              <div className="flex flex-col items-center justify-center min-h-screen -mt-16 text-center">
                <h1 className="text-2xl font-semibold mb-2">
                  Lu siapa?
                </h1>
                <p>Login sit lur ben bisa ndeleng.</p>
              </div>
            </SignedOut>
            <Toaster />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}